### ISSUE TITLE
Document Chrome Extension

### ISSUE THREAD

**Issue by NfNitLoop** [neilck/nostr-badges#10]
The [page] for the AKA Profiles Chrome extension links to this GitHub repository, but I don't see mention of the extension here.  How is it related to the rest of this project?

[page]: https://chromewebstore.google.com/detail/aka-profiles/ncmflpbbagcnakkolfpcpogheckolnad?pli=1

**Comment by neilck** [comment]
I need to update the general akaprofiles.com site to also include the extension link.
https://github.com/neilck/aka-extension
